%% TITLE_COMPONENT_CALCULATE_INITIALIZE
% creates and initialize the title for the component part of the tab body
% calculate,
% save the handle to handles.

rel_pos_title_component_calculate = [leftRatio_firstPoint,...
                1 - topRatio_firstPoint, ...
                lengthRatio_firstPoint, ...
                heightRatio_firstPoint];

pos_tabBody_calculate = get(handles.tabBody_calculate, 'Position');

h_label = label_Initialize(...
    handles.tabBody_calculate, '# Components', ...
    color_theme * fontColorRatio_tabBody, ...
    [fix(pos_tabBody_calculate(3) * rel_pos_title_component_calculate(1)) + 1, ...
    fix(pos_tabBody_calculate(4) * rel_pos_title_component_calculate(2)) + 1, ...
    fix(pos_tabBody_calculate(3) * rel_pos_title_component_calculate(3)), ...
    fix(pos_tabBody_calculate(4) * rel_pos_title_component_calculate(4))], ...
    fontSize_firstPoint, fontWeight_firstPoint, ...
    'adjusted');


set(h_label(1),'Tag','axes_title_component_calculate')
handles.axes_title_component_calculate = h_label(1);

set(h_label(2),'Tag','text_title_component_calculate')
handles.text_title_component_calculate = h_label(2);

guidata(hObject, handles);

clear h_array_label
clear rel_pos_title_component_calculate
