%% TOPLINE_MAINPANEL_INITIALIZE
% creates and initialize the top line at the top of the tab head in the main panel,
% save the handle to handles.

%% creates and initialize the separate line
pos_mainPanel = get(handles.mainPanel, 'Position');
h_topLine_mainPanel = uicontrol( ...
                'Parent', handles.mainPanel, ...
                'Style', 'text', ...
                'Tag', 'topLine_mainPanel', ...
                'Units', 'pixels', ...
                'Position', ...
                [fix(0.5 * width_gcf) - ...
                    fix(0.5 * lengthRatio_separateLine_mainPanel * width_gcf) + 1, ...
                pos_mainPanel(4) - 2, ...
                2 * fix(0.5 * lengthRatio_separateLine_mainPanel * width_gcf), ...
                thickPixel_separateLine_mainPanel], ...
                'BackgroundColor', backgroundColor_topLine_mainPanel ...
                );
clear pos_mainPanel
%% Save the handle of the bottom line of the tab head to the handles
handles.topLine_mainPanel = h_topLine_mainPanel;
clear h_topLine_mainPanel
guidata(hObject, handles);