%% VERTICALLINE_TABHEAD_INITIALIZE
% creates and initialize the vertical line between the tab pages in the tab
% head,
% save the handle to handles.

%% For-loop for number_tabPage - 1 line(s)
pos_tabHead = get(handles.tabHead, 'Position');
for ii = 1 : number_tabPage - 1
    %% creates and initialize the separate line
    h_verticalLine_tabHead_tmp = uicontrol( ...
                    'Parent', handles.tabHead, ...
                    'Style', 'text', ...
                    'Tag', 'verticalLine_tabHead', ...
                    'Units', 'pixels', ...
                    'Position', ...
                    [fix(ii * pos_tabHead(3) / number_tabPage) - ...
                        fix(0.5 * pos_tabHead(3) * thickPixel_verticalLine_tabHead / width_gcf) - 1, ...
                    fix(0.5 * pos_tabHead(4)) - fix(0.5 * pos_tabHead(4) * lengthRatio_verticalLine_tabHead), ...
                    thickPixel_verticalLine_tabHead, ...
                    2 * fix(0.5 * pos_tabHead(4) * lengthRatio_verticalLine_tabHead)], ...
                    'BackgroundColor', backgroundColor_verticalLine_tabHead ...
                    ); %#ok<NASGU>
    %% Save the handle of the bottom line of the tab head to the handles
    eval(['h_verticalLine_tabHead_',num2str(ii),' = h_verticalLine_tabHead_tmp;'])
    eval(['handles.verticalLine_tabHead_',num2str(ii),' = h_verticalLine_tabHead_',num2str(ii),';'])
    clear h_verticalLine_tabHead_tmp
    guidata(hObject, handles);
end
clear ii
clear pos_tabHead
