%% TAB_ALTER
% sets the value of the pressed tab page to 1,others to 0, 
% alters to the correspond tab body of the pressed tab page.

% set all icons to inactive and all tab bodies to invisible
function varargout = tab_alter(hObject, eventdata, handles) %#ok<INUSL,STOUT>
foregroundColor_tabPage_inactive = ...
    getappdata(0, 'ratio_foregroundColor_tabPage_inactive') * ...
    getappdata(0, 'foregroundColor_tabPage'); %#ok<NASGU>
item_tabPage = getappdata(0,'item_tabPage');

for ii = 1 : getappdata(0,'number_tabPage')
    % add background image to the icon
    eval(['h_tabPage_tmp = handles.tabPage_', item_tabPage{ii},';'])
    pos_h_tabPage_tmp = getpixelposition(h_tabPage_tmp, true);
    h_tabPage_icon_inactive_resized_add = ...
    add_icon_backgroundImage( ...
        getappdata(0, 'tabPage_icon_inactive_resized'), ...
        pos_h_tabPage_tmp, ...
        'adjusted', ...
        getappdata(0, 'eps'), getappdata(0, 'icon_transparency')); %#ok<NASGU>
    
    strEval = [ 'set(handles.tabBody_', item_tabPage{ii},...
                ',''Visible'', ''off''),', ...
                'set(handles.tabPage_', item_tabPage{ii}, ...
                ',''ForegroundColor'', foregroundColor_tabPage_inactive),', ...
                'set(handles.tabPage_', item_tabPage{ii}, ...
                ',''CData'', h_tabPage_icon_inactive_resized_add)'];
    eval(strEval)
    clear strEval
end
clear ii

clear foregroundColor_tabPage_inactive

% set the selected icon to active and the corresponding tab body to
% visible

% add background image to the icon
eval(['h_tabPage_tmp = handles.tabPage_', getappdata(0,'string_select_tabPage'),';'])
pos_h_tabPage_tmp = getpixelposition(h_tabPage_tmp, true);

h_tabPage_icon_active_resized_add = ...
add_icon_backgroundImage( ...
    getappdata(0, 'tabPage_icon_active_resized'), ...
    pos_h_tabPage_tmp, ...
    'adjusted', ...
    getappdata(0, 'eps'), getappdata(0,'icon_transparency')); %#ok<NASGU>


strEval = [ 'set(handles.tabBody_', getappdata(0,'string_select_tabPage'), ',''Visible'', ''on''),', ...
            'set(handles.tabPage_', getappdata(0,'string_select_tabPage'), ...
                ',''ForegroundColor'', getappdata(0, ''foregroundColor_tabPage'')),', ...
            'set(handles.tabPage_', getappdata(0,'string_select_tabPage'), ',''CData'', h_tabPage_icon_active_resized_add)'];
eval(strEval)
guidata(hObject, handles);

clear strEval
clear h_tabPage_tmp
end