%% LABEL_MIDDLE_INITIALIZE
% creates and initialize the label consisting of a pushbutton
% in the middle and at the centering position,
% sets the background image, 
% saves the handles to handles.

function h_label = label_middle_Initialize(...
    handle_parent, string_text, color_text, position_label, fontSize_text,...
    fontWeight_text, suffix)

% Create and initialize the label
h_label = uicontrol( ...
    'Parent', handle_parent, ...
    'Style', 'pushbutton', ...
    'Units', 'pixels', ...
    'Position', position_label, ...
    'FontUnits', 'pixels', ...
    'FontSize', fontSize_text, ...
    'FontWeight', fontWeight_text, ...
    'ForegroundColor', color_text, ...
    'String', string_text, ...
    'BackgroundColor', [0.941 0.941 0.941], ...
    'Enable', 'inactive');
    
    
% set the background image
if ~isempty(suffix)
    % find the height of hte resized and adjusted background image
    im_background_resized_adjusted = getappdata(0, ['im_background_resized_',suffix]);
    height_im_background_resized_adjusted = size(im_background_resized_adjusted,1);
    
    % find the absolute position of the label in pixels
    position_label_absolute = getpixelposition(h_label,true);
    % resize the image
    im_background_resized_adjusted_cut = ...
        im_background_resized_adjusted(...
            height_im_background_resized_adjusted - position_label_absolute(2) - ...
                position_label_absolute(4) + 2 : ...
            height_im_background_resized_adjusted - position_label_absolute(2) + 1, ...
            position_label_absolute(1) : position_label_absolute(1) + position_label_absolute(3) - 1, ...
            :);
    set(h_label, 'CData', im_background_resized_adjusted_cut)
end

end