%% LABEL_INITIALIZE
% creates and initialize the label consisting of an axes containing a text
% in the left and at the centering position,
% sets the background image, 
% saves the handles to handles.

function h_label = label_Initialize(...
    handle_parent, string_text, color_text, position_label, fontSize_text,...
    fontWeight_text, suffix)

% Create and initialize the label
h_axes = axes(...
    'Parent', handle_parent, ...
    'Units', 'pixels', ...
    'Position', position_label);
axis off
    
% set the background image
if ~isempty(suffix)
    % find the height of hte resized and adjusted background image
    im_background_resized_adjusted = getappdata(0,['im_background_resized_',suffix]);
    height_im_background_resized_adjusted = size(im_background_resized_adjusted,1);
    
    % find the absolute position of the label in pixels
    position_axes_absolute = getpixelposition(h_axes,true);
    % resize the image
    im_background_resized_adjusted_cut = ...
        im_background_resized_adjusted(...
            height_im_background_resized_adjusted - position_axes_absolute(2) - ...
                position_axes_absolute(4) + 2 : ...
            height_im_background_resized_adjusted - position_axes_absolute(2) + 1, ...
            position_axes_absolute(1) : position_axes_absolute(1) + position_axes_absolute(3) - 1, ...
            :);
        
    % set the background image
    imshow(im_background_resized_adjusted_cut)
end

h_text = text(0, 0.5 * (1 + position_label(4)), string_text, ...
            'Color', color_text, ...
            'FontUnits', 'pixels', ...
            'FontSize', fontSize_text, ...
            'FontWeight', fontWeight_text);

h_label = [h_axes, h_text];

end