%% BOTTOMLINE_MAINPANEL_INITIALIZE
% creates and initialize the bottom line at the bottom of the tab body in the main panel,
% save the handle to handles.

%% creates and initialize the separate line

h_bottomLine_mainPanel = uicontrol( ...
                'Parent', handles.mainPanel, ...
                'Style', 'text', ...
                'Tag', 'bottomLine_mainPanel', ...
                'Units', 'pixels', ...
                'Position', ...
                [fix(0.5 * width_gcf) - ...
                    fix(0.5 * lengthRatio_bottomLine_mainPanel * width_gcf) + 1, ...
                0 ,...
                2 * fix(0.5 * lengthRatio_bottomLine_mainPanel * width_gcf), ...
                thickPixel_bottomLine_mainPanel], ...
                'BackgroundColor', backgroundColor_bottomLine_mainPanel ...
                );
%% Save the handle of the bottom line of the tab head to the handles
handles.bottomLine_mainPanel = h_bottomLine_mainPanel;
clear h_bottomLine_mainPanel
guidata(hObject, handles);