%% SEPARATELINE_MAINPANEL_INITIALIZE
% creates and initialize the separate line between the tab head and the tab
% body in the main panel,
% save the handle to handles.

%% creates and initialize the separate line
pos_mainPanel = get(handles.mainPanel, 'Position');
h_separateLine_mainPanel = uicontrol( ...
                'Parent', handles.mainPanel, ...
                'Style', 'text', ...
                'Tag', 'separateLine_mainPanel', ...
                'Units', 'pixels', ...
                'Position', ...
                [fix(0.5 * width_gcf) - ...
                    fix(0.5 * lengthRatio_separateLine_mainPanel * width_gcf) + 1, ...
                fix(pos_mainPanel(4) * (1 - heightRatio_tabHead)) + 1, ...
                2 * fix(0.5 * lengthRatio_separateLine_mainPanel * width_gcf), ...
                thickPixel_separateLine_mainPanel], ...
                'BackgroundColor', backgroundColor_separateLine_mainPanel ...
                );
clear pos_mainPanel
%% Save the handle of the bottom line of the tab head to the handles
handles.separateLine_mainPanel = h_separateLine_mainPanel;
clear h_separateLine_mainPanel
guidata(hObject, handles);